
##cloudflare配置
cloudflare:
#cloudflare账号邮箱
 - x_email:  

   #域名(多个用逗号分隔)
   hostname: 
   
   #空间ID
   zone_id:
   
   #Global API Key
   api_key: 

#配置多个账号或域名,注意字段使用空格对齐，符合yaml格式要求 
# - x_email:  
#
#   #域名(多个用逗号分隔)
#   hostname: 
#   
#   #空间ID
#   zone_id:
#   
#   #Global API Key
#   api_key: 

##openwrt科学上网插件配置
#优选节点时是否自动停止科学上网服务 true: 自动停止 false: 不停止 默认为 true
pause: 
  true
#填写openwrt使用的是哪个科学上网客户端，填写对应的“数字”  默认为 1  客户端为passwall
# 1: passwall 2: passwall2 3: ShadowSocksR Plus+ 4: clash 5: openclash 6: bypass
clien: 
  1
#同一域名更新的ip数量(如果设置值大于实际搜出的ip数量，以实际ip数量为准)
multip:

#测速地址  
CFST_URL: 
  
#测速线程数量；越多测速越快，性能弱的设备 (如路由器) 请勿太高；(默认 200 最多 1000 )
CFST_N: 200
#延迟测速次数；单个 IP 延迟测速次数，为 1 时将过滤丢包的IP，TCP协议；(默认 4 次 )
CFST_T: 1
#下载测速数量；延迟测速并排序后，从最低延迟起下载测速的数量；(默认 10 个)
CFST_DN: 10
#平均延迟上限；只输出低于指定平均延迟的 IP，可与其他上限/下限搭配；(默认9999 ms 这里推荐配置250 ms)
CFST_TL: 250
#平均延迟下限；只输出高于指定平均延迟的 IP，可与其他上限/下限搭配、过滤假墙 IP；(默认 0 ms 这里推荐配置40)
CFST_TLL: 40
#下载速度下限；只输出高于指定下载速度的 IP，凑够指定数量 [-dn] 才会停止测速；(默认 0.00 MB/s 这里推荐5.00MB/s)
CFST_SL: 5
#是否按国家代码做分组筛选(是: true,否: false)
CCFLAG: true
#需要指定的国家代码,多个用逗号分隔(eg. US,JP)
CCODE: 
#CF服务器对应端口
CF_ADDR: 443

#推送开关, 1:TG, 2:WX, 3.both.
sendType:
   3

##TG推送设置
#（填写即为开启推送，未填写则为不开启）
#TG机器人token 例如：123456789: ABCDEFG...
telegramBotToken:  
  
telegramBotUserId: 
  
 
#微信推送, 关注微信公众号[方糖]，取得sendKey
sendKey:

